### ISSUE TITLE
Crawler To-Do List

### ISSUE THREAD

**Issue by brianignacio5** [moritzschaefer/the-search-engine#1]
# Details of Web Crawler

Define the following functions which performs the crawler steps.
*Database crawler:* Loop in charge to pass the url of authors list in http://dblp.uni-trier.de/pers?pos=# starting from 1 and incrementing 300

## Functionality

1. [x] Loop in charge to pass the url of authors list in http://dblp.uni-trier.de/pers?pos=# starting from 1 and incrementing 300.
2. [x] Loop in charge to pass the url of journals list in http://dblp.uni-trier.de/db/journals/?pos=# starting from 1 and incrementing 100.
3. [x] Loop in charge to pass the url of conferences list in http://dblp.uni-trier.de/db/conf/?pos=# starting from 1 and incrementing 100.
4. [x] Design decision: A whole list of Authors URLs or a segmented one. ? Suppose a whole list, then (1) produce a whole list and pass this list to (3).
5. [x] Receive list of URL and call crawl_site() to create the whole/partial raw directory.
6. [x] Test crawl_site on Journals and Conferences
7. [x] Test crawl_url on Journals and Conferences

**Comment by moritzschaefer** [comment]
Answor to 4.:
I would do like this:
n=1
while True:
   300authors = crawl_urls(http://dblp.uni-trier.de/pers?pos=n)
   for author_url in 300authors:
      crawl_site(author_url)
   n += 300

**Comment by moritzschaefer** [comment]
TODO for bian: the two tests :). Just duplicate the code for authors
